#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/spanning
#
# IDENTIFICATION
#    src/backend/access/spanning/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/spanning
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	spanning_ddl.o \
	spanning_exec.o

include $(top_srcdir)/src/backend/common.mk
